---
# Source: wordpress-gcp/templates/k8s-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sql-wp-ksa-wi
  annotations:
    iam.gke.io/gcp-service-account: sql-wp-sa@alexbu-20210402-dev.iam.gserviceaccount.com
---
# Source: wordpress-gcp/templates/k8s-sql-db-credentials.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-cloudsql-db-credentials
stringData:
  projectId: alexbu-20210402-dev
  username: wordpress
  password: change-me
  connectionName: us-central1:wp-db
---
# Source: wordpress-gcp/templates/gcp-sql-api.yaml
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: sqladmin.googleapis.com
---
# Source: wordpress-gcp/templates/k8s-external-load-balancer.yaml
apiVersion: v1
kind: Service
metadata:
  name: wordpress-external
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: web
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
---
# Source: wordpress-gcp/templates/k8s-stateful-set.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  serviceName: "wordpress"
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: sql-wp-ksa-wi
      containers:
      - name: wordpress
        resources: 
          limits:
            cpu: 200m
            memory: 100Mi
        image: wordpress:5.2.2-apache
        imagePullPolicy: IfNotPresent
        env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:3306
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-cloudsql-db-credentials
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-cloudsql-db-credentials
              key: password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-volume
          mountPath: /var/www/html
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 20
          successThreshold: 1
      - name: cloudsql-proxy
        resources:
          limits:
            cpu: "200m"
            memory: "100Mi"
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        env:
          - name: CONNECTION_NAME
            valueFrom:
              secretKeyRef:
                name: wordpress-cloudsql-db-credentials
                key: connectionName
          - name: PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: wordpress-cloudsql-db-credentials
                key: projectId
        command: ["/cloud_sql_proxy",
                  "-instances=$(PROJECT_ID):$(CONNECTION_NAME)=tcp:3306"]
  volumeClaimTemplates:
    - metadata:
        name: wordpress-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
# Source: wordpress-gcp/templates/gcp-wi-policy.yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: sql-wp-sa-wi-policy
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: sql-wp-sa
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:alexbu-20210402-dev.svc.id.goog[service-a/sql-wp-ksa-wi]
---
# Source: wordpress-gcp/templates/gcp-sql-policy-member.yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: sql-wp-sa-project-policymember
spec:
  member: serviceAccount:sql-wp-sa@alexbu-20210402-dev.iam.gserviceaccount.com
  role: roles/cloudsql.client
  resourceRef:
    kind: Project
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    external: alexbu-20210402-dev
---
# Source: wordpress-gcp/templates/gcp-sql-service-account.yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: sql-wp-sa
spec:
  displayName: Service Account for WordPress Config Connector Sample
---
# Source: wordpress-gcp/templates/gcp-sql-db.yaml
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: wordpress
spec:
  charset: utf8
  instanceRef:
    name: wp-db
---
# Source: wordpress-gcp/templates/gcp-sql-instance.yaml
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: wp-db
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  settings:
    tier: db-f1-micro
---
# Source: wordpress-gcp/templates/gcp-sql-user.yaml
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: wordpress
spec:
  instanceRef:
    name: wp-db
  host: "%"
  password:
    valueFrom:
      secretKeyRef:
        name: wordpress-cloudsql-db-credentials
        key: password
